# Generated by Django 4.2 on 2024-08-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_category_subcategories_category_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='properties',
            field=models.TextField(blank=True, null=True, verbose_name='Properties'),
        ),
    ]
