# Generated by Django 4.2 on 2024-08-11 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'permissions': [('is_owner', 'Is owner')], 'verbose_name': 'Staff', 'verbose_name_plural': 'Staffs'},
        ),
    ]
