# Generated by Django 4.2 on 2024-08-11 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_alter_staff_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'permissions': [('is_owner', 'Is owner'), ('is_manager', 'Is manager')], 'verbose_name': 'Staff', 'verbose_name_plural': 'Staffs'},
        ),
    ]
