# Generated by Django 4.2 on 2024-08-27 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('dashboard', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('text', models.TextField(verbose_name='Text')),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Rejected', 'Rejected'), ('Approved', 'Approved'), ('Pending', 'Pending')], default='Pending', max_length=100, verbose_name='Status')),
                ('ShopProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comments', to='dashboard.shopproduct', verbose_name='Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.customer', verbose_name='User')),
            ],
        ),
    ]
