# Generated by Django 4.2 on 2024-08-07 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('payment', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Total Payment')),
                ('delivered', models.CharField(choices=[('Preparing', 'Preparing'), ('Sending', 'Sending'), ('Completed', 'Completed')], max_length=100, verbose_name='Order Status')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('total_price', models.PositiveIntegerField(default=0, verbose_name='Total Price')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.order', verbose_name='Order')),
            ],
        ),
    ]
