# Generated by Django 4.2 on 2024-08-07 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('dashboard', '0001_initial'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.shopproduct', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='customers.customer', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='shop_product',
            field=models.ManyToManyField(related_name='orders_shop_product', through='cart.ProductOrder', to='dashboard.shopproduct'),
        ),
    ]
