# Generated by Django 4.2 on 2024-08-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Total Price'),
        ),
    ]
