# Generated by Django 4.2 on 2024-08-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_order_payment_alter_productorder_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Order Address'),
        ),
    ]
